### ISSUE TITLE
Reorganize products and home page enhancement

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/opensquare-network.github.io#46]
## Products page

Classify products into 3 groups:

1. Governance platforms
    - SubSquare
    - off-chain voting 
2. Explorers
    - dotreasury
    - Statescan
3. Collaboration platforms
    - Paid QA
    - Bounties
    - CoinAsk

And remove odes from product list.

`Comming soon` -> `TBD`

## Home page

Slogan: Empower Web3 Collaboration with Blockchain
Resort the items in 'We build for collaborations': 
1. paid QA
2. Bounties
3. Short-term employment
4. Customized collaboratioin

**Comment by Popoulosss** [comment]
Homepage

- [ ] Slogan: Empower Web3 Collaboration with Blockchain

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3085%3A688040

preview
![image](https://user-images.githubusercontent.com/59445675/151659650-4c297b7f-ef17-41e9-9c02-a4011f18c7f7.png)

**Comment by Popoulosss** [comment]
Homepage

- [ ] Resort the items in 'We build for collaborations'

1. Paid QA
2. Bounties
3. Short-term employment
4. Customized collaboratioin

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3085%3A688051

preview
![image](https://user-images.githubusercontent.com/59445675/151659704-2014d48a-32f7-4331-8a78-0626b8904946.png)

**Comment by Popoulosss** [comment]
### Products page

- [ ] Classify products into 3 groups and modify layout
- [ ] Remove odes from product list

1. Governance platforms
    - SubSquare
    - off-chain voting 
2. Explorers
    - dotreasury
    - Statescan
3. Collaboration platforms
    - Paid QA
    - Bounties
    - CoinAsk

figma link
https://www.figma.com/file/vqpglMGW8psHKB00eIVDUV/OpenSquare?node-id=3213%3A17152

preview
![image](https://user-images.githubusercontent.com/59445675/151659762-5f6318e5-afdf-4bb5-8e39-88dad537ab74.png)

**Comment by Popoulosss** [comment]
### Products page

- [ ] Fix header UI

preview
![image](https://user-images.githubusercontent.com/59445675/151659805-7ca98cba-8fc5-4b83-af84-c39e0d2c2187.png)
